#!/bin/bash

. $PADIR/utils

WORK_DIR=`pwd`

OUT_DIR=$WORK_DIR/obj_out
CPUS=`nproc`
# Use half of server resource to build
THREADs=-j$(expr $CPUS / 2)
CONFIG_F=config

MACHINE_NAME=""
KERNEL_ARCH=""
TOOLCHAIN_ARCH=""
KERNEL_DIR=""

YOCTO_BUILD_WORK=`find . -maxdepth 2 -name "work"`
YOCTO_BUILD_WORK_SHARED=`find . -maxdepth 2 -name "work-shared"`
get_machine_name() {
    MACHINE_NAME=`cat conf/local.conf | grep ^MACHINE | head -n 1 | cut -d '=' -f2 | cut -d '"' -f2`
    echo_c SC_BLUE "MACHINE_NAME: $MACHINE_NAME"
}

get_layer(){
    find layers -maxdepth 3 -name "machine" -exec grep -Hrn $MACHINE_NAME {} \; | cut -d ':' -f1 | sort | uniq
}

get_kernel(){
    KERNEL_DIR=`find $YOCTO_BUILD_WORK_SHARED/$MACHINE_NAME -name "kernel-source"`
}

get_arch(){
    case "$MACHINE_NAME" in
	"marvell-cn96xx" | "marvell-cn10xxx" | "marvell-cn106xx" | "nxp-imx8")
	    KERNEL_ARCH=arm64
	    TOOLCHAIN_ARCH=aarch64
	    echo_c SC_BLUE "KERNEL_ARCH: $KERNEL_ARCH"
	    echo_c SC_BLUE "TOOLCHAIN_ARCH: $TOOLCHAIN_ARCH"
	    ;;
	"intel-x86-64")
	    KERNEL_ARCH=x86_64
	    TOOLCHAIN_ARCH=x86_64
	    echo_c SC_BLUE "KERNEL_ARCH: $KERNEL_ARCH"
	    echo_c SC_BLUE "TOOLCHAIN_ARCH: $TOOLCHAIN_ARCH"
	    ;;
	"nxp-imx6" | "nxp-imx7")
	    KERNEL_ARCH=arm
	    TOOLCHAIN_ARCH=arm
	    echo_c SC_BLUE "KERNEL_ARCH: $KERNEL_ARCH"
	    echo_c SC_BLUE "TOOLCHAIN_ARCH: $TOOLCHAIN_ARCH"
	    ;;
	*)
	    echo_c SC_RED "Can't get architecture of machine [$MACHINE_NAME]... please fix me."
	    exit 1
    esac
}

set_env() {
    get_machine_name
    get_arch
    get_kernel

    if [ ! -d $OUT_DIR ]; then
	mkdir -p $OUT_DIR
    fi

    if [ -f bisect.conf ]; then
	echo_c SC_GREEN "Read ppre from config."
	PPRE=`cat bisect.conf`
    else
	echo_c SC_GREEN "Try to find a ppre..."
	PPRE=`find $YOCTO_BUILD_WORK -maxdepth 4 -name "recipe-sysroot-native" | grep linux-yocto`
	if [ "x$PPRE" == "x" ] ; then
	    echo_c SC_RED "I can't found recipe-sysroot-native dir..."
	    exit 1
	fi
	echo $PPRE > bisect.conf
    fi
    # we need some tools provided by sysroot-native, e.g. pahole
    export PATH=$PATH:$WORK_DIR/$PPRE/usr/bin
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WORK_DIR/$PPRE/usr/lib
    export C_INCLUDE_PATH=$C_INCLUDE_PATH:$WORK_DIR/$PPRE/usr/include
    export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$WORK_DIR/$PPRE/usr/include
    # add cross tools to PATH
    pushd $WORK_DIR/$PPRE/usr/bin/
    temp_CROSSDIR=`find . -maxdepth 1 | grep wrs-linux`
    popd

    CROSSDIR=$WORK_DIR/$PPRE/usr/bin/${temp_CROSSDIR}
    export PATH=$PATH:${CROSSDIR}
    echo "crossdir = [$CROSSDIR]"
    pushd ${CROSSDIR}
    CROSS=`find . -maxdepth 1 | ls | awk 'NR==1{a=$0;next}{for(i=1;i<=length(a);i++)if(substr(a,i,1)!=substr($0,i,1)){a=substr(a,1,i-1);break}}END{print a}'`
    popd
}

do_allyesmake() {
    echo_c SC_B_GREEN "progress: [allyes make]."
    rm -rf $OUT_DIR
    make -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR allyesconfig
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR > /dev/null
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi
    exit 0
}

do_menuconfig() {
    echo_c SC_B_GREEN "progress: [menuconfig]."
    cp $CONFIG_F $OUT_DIR/.config
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR menuconfig
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    else 
	cp $OUT_DIR/.config $CONFIG_F 
    fi
    exit 0
}

do_make() {
    echo_c SC_B_GREEN "progress: [make]."
    cp $CONFIG_F $OUT_DIR/.config
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR
    if [ "$?" != "0" ]; then
	echo_c SC_RED "make failed."
	return 1
    fi
}

do_mod_install() {
    echo_c SC_B_GREEN "progress: [install modules]."
    rm -rf $OUT_DIR/__mod
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR modules_install INSTALL_MOD_PATH=$OUT_DIR/__mod > /dev/null
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi

    echo_c SC_B_GREEN "progress: [package modules]."
    pushd $OUT_DIR/__mod/lib/modules > /dev/null
    pushd * > /dev/null
    rm build source
    popd > /dev/null
    MOD_V=`ls`
    tar -zcvf $MOD_V.tar.gz $MOD_V > /dev/null 2>&1
    module_package=`pwd -P`
    echo_c SC_B_BLUE "modules location: $module_package/$MOD_V.tar.gz"
    popd > /dev/null
    exit 0
}

do_bisect() {
    echo_c SC_B_GREEN "progress: [bisect]."

    patches_tmp=""
    patches_failed=0
    while true
    do
	pushd $KERNEL_DIR
	$PADIR/flow/apply 1
	if [ "$?" != "0" ]; then
	    break
	fi
	popd

	do_make
	if [ "$?" != "0" ]; then
	    patches_tmp="$patches_tmp $curr"
	    patches_failed=$(($patches_failed + 1))
	else
	    echo_c SC_GREEN "Automatically save .config as config."
	    cp $OUT_DIR/.config $CONFIG_F 
	    patches_tmp=""
	    patches_failed=0
	fi

	if [ $patches_failed -gt 1 ]; then
	    echo_c SC_RED "2 patches failed. exit"
	    echo "$patches_tmp"
	    exit 1
	fi
    done
}

do_my_command() {
    echo crossdir == ${CROSSDIR}
    echo cross == ${CROSS}
    ${CROSS}gcc --version
    ${CROSS}gcc --help
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:tmp-glibc/work/octeontx2-wrs-linux/bash/5.1.16-r0/recipe-sysroot/usr/lib
    export LIBRARY_PATH=$LIBRARY_PATH:tmp-glibc/work/octeontx2-wrs-linux/bash/5.1.16-r0/recipe-sysroot/usr/lib
    ${CROSS}gcc -I tmp-glibc/work/octeontx2-wrs-linux/bash/5.1.16-r0/recipe-sysroot/usr/include test.c -c test.o
    ${CROSS}gcc -Ltmp-glibc/work/octeontx2-wrs-linux/bash/5.1.16-r0/recipe-sysroot/usr/lib -Btmp-glibc/work/octeontx2-wrs-linux/bash/5.1.16-r0/recipe-sysroot/usr/lib -lc test.o -o test
    if [ "$?" != "0" ]; then
        echo_c SC_RED "failed."
        exit 1
    fi
    exit 0
}

set_env

if [ "$#" == "0" ]; then
    do_bisect
fi

case "$1" in
    "make")
	do_make
	do_mod_install
	;;
    "menuconfig")
	do_menuconfig
	;;
    "allyesmake")
	do_allyesmake
	;;
    "my_command")
	do_my_command
	;;
    *)
	echo_c SC_B_CYAN "Usage1: $0"
	echo_c SC_B_CYAN "\tThis usage will run bisect Verify progress."
	echo
	echo_c SC_B_CYAN "Usage2: $0 [cmd]"
	echo_c SC_B_CYAN "cmd:"
	echo_c SC_B_CYAN "\tmake menuconfig allyesmake"
	exit -1
esac
