#!/bin/bash

PADIR=$(dirname $(readlink -f $0))
. $PADIR/utils

which apply > /dev/null 2>&1
if [ "$?" != "0" ]; then
    source $PADIR/pa.init
fi

WORK_DIR=`pwd`
#
ARCH=x86_64
#ARCH=arm64
#
if [ "$ARCH" = "x86_64" ]; then
    toolchain_arch=x86_64
elif [ "$ARCH" = "arm64" ]; then
    toolchain_arch=aarch64
else
    echo_c SC_RED "Can't get toolchain_arch, please add..."
    exit 1
fi
KERNEL_DIR=`find $WORK_DIR/tmp-glibc/work-shared/ -maxdepth 2 -name "kernel-source"`
OUT_DIR=$WORK_DIR/obj_out
THREADs=-j48
CONFIG_F=config

set_env() {
    if [ ! -d $OUT_DIR ]; then
	mkdir -p $OUT_DIR
    fi

    if [ -f bisect.conf ]; then
	echo_c SC_GREEN "Read ppre from config."
	PPRE=`cat bisect.conf`
    else
	echo_c SC_GREEN "Try to find a ppre..."
	PPRE=`find tmp-glibc/work -maxdepth 4 -name "recipe-sysroot-native" | grep linux-yocto`
	if [ "x$PPRE" == "x" ] ; then
	    echo_c SC_RED "I can't found recipe-sysroot-native dir..."
	    exit 1
	fi
	echo $PPRE > bisect.conf
    fi
    # we need some tools provided by sysroot-native, e.g. pahole
    export PATH=$PATH:$WORK_DIR/$PPRE/usr/bin
    # add cross tools to PATH
    pushd $WORK_DIR/$PPRE/usr/bin/
    temp_CROSSDIR=`find . -maxdepth 1 | grep wrs-linux`
    popd

    CROSSDIR=$WORK_DIR/$PPRE/usr/bin/${temp_CROSSDIR}
    export PATH=$PATH:${CROSSDIR}
    echo "crossdir = [$CROSSDIR]"
    pushd ${CROSSDIR}
    CROSS=`find . -maxdepth 1 | ls | awk 'NR==1{a=$0;next}{for(i=1;i<=length(a);i++)if(substr(a,i,1)!=substr($0,i,1)){a=substr(a,1,i-1);break}}END{print a}'`
    popd
}

do_allyesmake() {
    echo_c SC_B_GREEN "progress: [allyes make]."
    rm -rf $OUT_DIR
    make -C $KERNEL_DIR ARCH=$ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR allyesconfig
    make $THREADs -C $KERNEL_DIR ARCH=$ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR > /dev/null
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi
    exit 0
}

do_menuconfig() {
    echo_c SC_B_GREEN "progress: [menuconfig]."
    cp $CONFIG_F $OUT_DIR/.config
    make $THREADs -C $KERNEL_DIR ARCH=$ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR menuconfig
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    else 
	cp $OUT_DIR/.config $CONFIG_F 
    fi
    exit 0
}

do_make() {
    echo_c SC_B_GREEN "progress: [make]."
    cp $CONFIG_F $OUT_DIR/.config
    make $THREADs -C $KERNEL_DIR ARCH=$ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi
    make $THREADs -C $KERNEL_DIR ARCH=$ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR modules_install INSTALL_MOD_PATH=$OUT_DIR/__mod/
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi
    exit 0
}

do_bisect() {
    echo_c SC_B_GREEN "progress: [bisect]."

    patches_tmp=""
    patches_failed=0
    while true
    do
	pushd $KERNEL_DIR
	apply 1
	if [ "$?" != "0" ]; then
	    break
	fi
	popd

	cp $CONFIG_F $OUT_DIR/.config
	make $THREADs -C $KERNEL_DIR ARCH=$ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR
	if [ "$?" != "0" ]; then
	    echo_c SC_RED "failed."
	    patches_tmp="$patches_tmp $curr"
	    patches_failed=$(($patches_failed + 1))
	else
	    cp $OUT_DIR/.config $CONFIG_F 
	    patches_tmp=""
	    patches_failed=0
	fi

	if [ $patches_failed -gt 1 ]; then
	    echo_c SC_RED "2 patches failed. exit"
	    echo "$patches_tmp"
	    exit 1
	fi
    done
}

set_env

if [ "$#" == "0" ]; then
    do_bisect
fi

case "$1" in
    "make")
	do_make
	;;
    "menuconfig")
	do_menuconfig
	;;
    "allyesmake")
	do_allyesmake
	;;
    *)
	echo_c SC_B_CYAN "Usage1: $0"
	echo_c SC_B_CYAN "\tThis usage will run bisect Verify progress."
	echo
	echo_c SC_B_CYAN "Usage2: $0 [cmd]"
	echo_c SC_B_CYAN "cmd:"
	echo_c SC_B_CYAN "\tmake menuconfig allyesmake"
	exit -1
esac
