#!/bin/bash

PADIR=$(dirname $(readlink -f $0))
. $PADIR/utils

WORK_DIR=`pwd`

OUT_DIR=$WORK_DIR/obj_out
THREADs=-j48
CONFIG_F=config

MACHINE_NAME=""
KERNEL_ARCH=""
TOOLCHAIN_ARCH=""
KERNEL_DIR=""

get_machine_name() {
    MACHINE_NAME=`cat conf/local.conf | grep ^MACHINE | cut -d '=' -f2 | cut -d '"' -f2`
    echo_c SC_BLUE "MACHINE_NAME: $MACHINE_NAME"
}

get_layer(){
    find layers -maxdepth 3 -name "machine" -exec grep -Hrn $MACHINE_NAME {} \; | cut -d ':' -f1 | sort | uniq
}

get_kernel(){
    KERNEL_DIR=`find $WORK_DIR/tmp-glibc/work-shared/$MACHINE_NAME -name "kernel-source"`
}

get_arch(){
    case "$MACHINE_NAME" in
	"marvell-cn96xx" | "marvell-cn10xxx" | "marvell-cn106xx")
	    KERNEL_ARCH=arm64
	    TOOLCHAIN_ARCH=aarch64
	    echo_c SC_BLUE "KERNEL_ARCH: $KERNEL_ARCH"
	    echo_c SC_BLUE "TOOLCHAIN_ARCH: $TOOLCHAIN_ARCH"
	    ;;
	"intel-x86-64")
	    KERNEL_ARCH=x86_64
	    TOOLCHAIN_ARCH=x86_64
	    echo_c SC_BLUE "KERNEL_ARCH: $KERNEL_ARCH"
	    echo_c SC_BLUE "TOOLCHAIN_ARCH: $TOOLCHAIN_ARCH"
	    ;;
	*)
	    echo_c SC_RED "Can't get architecture of machine [$MACHINE_NAME]... please fix me."
	    exit 1
    esac
}

set_env() {
    get_machine_name
    get_arch
    get_kernel

    if [ ! -d $OUT_DIR ]; then
	mkdir -p $OUT_DIR
    fi

    if [ -f bisect.conf ]; then
	echo_c SC_GREEN "Read ppre from config."
	PPRE=`cat bisect.conf`
    else
	echo_c SC_GREEN "Try to find a ppre..."
	PPRE=`find tmp-glibc/work -maxdepth 4 -name "recipe-sysroot-native" | grep linux-yocto`
	if [ "x$PPRE" == "x" ] ; then
	    echo_c SC_RED "I can't found recipe-sysroot-native dir..."
	    exit 1
	fi
	echo $PPRE > bisect.conf
    fi
    # we need some tools provided by sysroot-native, e.g. pahole
    export PATH=$PATH:$WORK_DIR/$PPRE/usr/bin
    # add cross tools to PATH
    pushd $WORK_DIR/$PPRE/usr/bin/
    temp_CROSSDIR=`find . -maxdepth 1 | grep wrs-linux`
    popd

    CROSSDIR=$WORK_DIR/$PPRE/usr/bin/${temp_CROSSDIR}
    export PATH=$PATH:${CROSSDIR}
    echo "crossdir = [$CROSSDIR]"
    pushd ${CROSSDIR}
    CROSS=`find . -maxdepth 1 | ls | awk 'NR==1{a=$0;next}{for(i=1;i<=length(a);i++)if(substr(a,i,1)!=substr($0,i,1)){a=substr(a,1,i-1);break}}END{print a}'`
    popd
}

do_allyesmake() {
    echo_c SC_B_GREEN "progress: [allyes make]."
    rm -rf $OUT_DIR
    make -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR allyesconfig
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR > /dev/null
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi
    exit 0
}

do_menuconfig() {
    echo_c SC_B_GREEN "progress: [menuconfig]."
    cp $CONFIG_F $OUT_DIR/.config
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR menuconfig
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    else 
	cp $OUT_DIR/.config $CONFIG_F 
    fi
    exit 0
}

do_make() {
    echo_c SC_B_GREEN "progress: [make]."
    cp $CONFIG_F $OUT_DIR/.config
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi
    make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR modules_install INSTALL_MOD_PATH=$OUT_DIR/__mod/
    if [ "$?" != "0" ]; then
	echo_c SC_RED "failed."
	exit 1
    fi
    exit 0
}

do_bisect() {
    echo_c SC_B_GREEN "progress: [bisect]."

    patches_tmp=""
    patches_failed=0
    while true
    do
	pushd $KERNEL_DIR
	apply 1
	if [ "$?" != "0" ]; then
	    break
	fi
	popd

	cp $CONFIG_F $OUT_DIR/.config
	make $THREADs -C $KERNEL_DIR ARCH=$KERNEL_ARCH CROSS_COMPILE=$CROSS O=$OUT_DIR
	if [ "$?" != "0" ]; then
	    echo_c SC_RED "failed."
	    patches_tmp="$patches_tmp $curr"
	    patches_failed=$(($patches_failed + 1))
	else
	    cp $OUT_DIR/.config $CONFIG_F 
	    patches_tmp=""
	    patches_failed=0
	fi

	if [ $patches_failed -gt 1 ]; then
	    echo_c SC_RED "2 patches failed. exit"
	    echo "$patches_tmp"
	    exit 1
	fi
    done
}

set_env

if [ "$#" == "0" ]; then
    do_bisect
fi

case "$1" in
    "make")
	do_make
	;;
    "menuconfig")
	do_menuconfig
	;;
    "allyesmake")
	do_allyesmake
	;;
    *)
	echo_c SC_B_CYAN "Usage1: $0"
	echo_c SC_B_CYAN "\tThis usage will run bisect Verify progress."
	echo
	echo_c SC_B_CYAN "Usage2: $0 [cmd]"
	echo_c SC_B_CYAN "cmd:"
	echo_c SC_B_CYAN "\tmake menuconfig allyesmake"
	exit -1
esac
