#!/bin/bash

WORK_DIR=$(dirname $(readlink -f $0))
. $WORK_DIR/../utils

patches_dir=.patches.todo
patched_dir=.patches.over
ref_dir=.patches.ref

create_dir $patched_dir

function do_patch() {
    echo_c SC_GREEN "op: $1"
    git am $1
    if [ "$?" = "0" ]; then
	mv $1 $patched_dir/
    else 
	git apply --reject $1
	echo 
	git status --no-ahead-behind
	echo_c SC_RED "err: $1"
	echo 
	exit 8;
    fi
}

if [ $# -gt 0 ]; then
    if grep '^[[:digit:]]*$' <<< "$1"; then
	# $1 is a num
	patch_num=`ls $patches_dir/*.patch | wc -l`
	echo_c SC_GREEN "There are $patch_num patches in $patches_dir"
	if [ $1 -le $patch_num ]; then
	    patch_list=`ls $patches_dir/*.patch | sort | head -n $1`
	    for f in $patch_list
	    do
		do_patch $f
	    done
	else
	    echo_c SC_RED "这儿没那么多patch !."
	    exit 2
	fi
    else
	# $1 is patch path
	if [ ! -f $1 ]; then
	    echo_c SC_RED "$1 is not exists.."
	    exit 2
	fi
	do_patch $1
    fi
else
    patch_list=`ls $patches_dir/*.patch | sort`
    if [ "$patch_list" = "" ]; then
        echo_c SC_GREEN "There is no patches in this dir."
        exit 2
    fi
    for f in $patch_list
    do
	do_patch $f
    done

    exit 0;
fi
