#!/bin/bash

WORK_DIR=$(dirname $(readlink -f $0))
. $WORK_DIR/../utils

create_dir patches.reserve

git checkout .
clean_rej
git am --abort

mv -v `ls patches.todo/*.patch | head -n 1` patches.reserve
